### ISSUE TITLE
Add support of JuMP variable/constraint names on GAMS level

### ISSUE THREAD

**Issue by MartinBonde** [GAMS-dev/gams.jl#12]
I am sending a JuMP model to CONOPT4 using GAMS.jl and get an error/warning:
** Error in Square System: A variable tries to exceed its bound.

This is perfectly familiar and I get more information by looking in the generated moi.lst file
to find out which variable is the culprit:

**** ERRORS/WARNINGS IN VARIABLE x382
     1 error(s): The variable tries to exceed its bound.

Is there any way of identifying what “x382” refers to in the above?

miles.lubin on [discourse ](https://discourse.julialang.org/t/identifying-variables-in-gams-jl-errors-how-do-i-look-up-jump-variables-from-auto-generated-name-x/74851) suggested opening an issue since "JuMP does provide the capability to pass variable names down to the solver."

**Comment by renkekuhlmann** [comment]
Yeah, there is currently no feature to look up the autogenerated names. I agree that it would be useful to use the JuMP variable names on the GAMS level. I'll look into it. Thanks for the feature request.

**Comment by renkekuhlmann** [comment]
I added writing the variable and constraint (only linear and quadratic) names that the user passes to the generated GAMS model with v0.3.0 - along with some other updates. Note however, that GAMS is very restrictive when it comes to variable naming and that something like `x[1,2]` or `β` is not allowed in GAMS source. Therefore, forbidden characters are replaced by `_`. I can then happen that the name is invalid because it will start with `_`, e.g. if you are using unicode symbols. In that case GAMS.jl should fall back to generic names. I hope this solution is fine for debugging. The generated files were never meant to be beautiful 😉 

Version 0.3.0 should be available in a moment.

**Comment by MartinBonde** [comment]
Thanks! That should work except for the issue with not just illegal characters, but also case insensitivity of GAMS. Would it be possible to access some mapping (e.g. a dict) between the two? The users can easily do a search and replace of any error message or LST file if needed.

**Comment by renkekuhlmann** [comment]
Okay, done with the latest commit, see https://github.com/GAMS-dev/gams.jl#gams-names-vs-jump-names. Version 0.3.1 will be available soon.

**Comment by MartinBonde** [comment]
Looks great! I did not realize there was an issue with naming restrictions when I opened the issue, but this seems like a good solution. I look forward to trying it.
